[features]
seeds = false
skip-lint = false
[programs.localnet]
vault_anchor = "EU8pUSscGp8tziAHcCWf3Fs5x1oist46SjwyfheGT1My"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/savvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
